---
ecmaFeatures:
  arrowFunctions: true
  binaryLiterals: true
  blockBindings: true
  classes: true
  defaultParams: true
  destructuring: true
  experimentalObjectRestSpread: true
  forOf: true
  generators: true
  globalReturn: false
  jsx: true
  modules: false
  objectLiteralComputedProperties: true
  objectLiteralDuplicateProperties: false
  objectLiteralShorthandMethods: true
  objectLiteralShorthandProperties: true
  octalLiterals: true
  regexUFlag: true
  regexYFlag: false
  restParams: true
  spread: true
  superInFunctions: true
  templateStrings: true
  unicodeCodePointEscapes: true
env:
  amd: true
  browser: true
  commonjs: true
  es6: true
  jasmine: true
  node: true
extends: eslint:recommended
parser: babel-eslint
plugins:
- jasmine
rules:
  arrow-body-style:
  - 2
  - as-needed
  block-scoped-var: 2
  brace-style:
  - 2
  - 1tbs
  - allowSingleLine: true
  camelcase: 1
  comma-spacing:
  - 2
  - after: true
    before: false
  comma-style:
  - 2
  - last
  complexity:
  - 2
  - 5
  computed-property-spacing:
  - 2
  - never
  consistent-return: 2
  consistent-this:
  - 1
  - self
  constructor-super: 2
  curly:
  - 2
  - multi-line
  default-case: 0
  dot-location:
  - 2
  - property
  eqeqeq:
  - 2
  - smart
  generator-star-spacing:
  - 2
  - after: false
    before: true
  guard-for-in: 1
  indent:
  - 1
  - 2
  - SwitchCase: 1
  init-declarations: 0
  jsx-quotes: 1
  max-depth:
  - 1
  - 3
  max-len:
  - 1
  - 120
  - 2
  max-nested-callbacks:
  - 2
  - 3
  max-params:
  - 2
  - 3
  max-statements:
  - 1
  - 20
  new-parens: 1
  no-alert: 0
  no-array-constructor: 2
  no-arrow-condition: 2
  no-caller: 2
  no-case-declarations: 1
  no-catch-shadow: 2
  no-class-assign: 2
  no-console: 0
  no-const-assign: 2
  no-debugger: 0
  no-div-regex: 2
  no-dupe-class-members: 2
  no-else-return: 1
  no-empty-label: 2
  no-empty-pattern: 2
  no-eq-null: 0
  no-eval: 2
  no-extend-native: 2
  no-extra-bind: 2
  no-floating-decimal: 2
  no-implicit-coercion: 2
  no-implied-eval: 2
  no-invalid-this: 2
  no-iterator: 2
  no-label-var: 2
  no-labels: 0
  no-lone-blocks: 2
  no-lonely-if: 1
  no-loop-func: 2
  no-magic-numbers: 1
  no-multi-spaces: 0
  no-multi-str: 2
  no-multiple-empty-lines: 1
  no-native-reassign: 2
  no-nested-ternary: 2
  no-new: 0
  no-new-func: 2
  no-new-object: 2
  no-new-wrappers: 2
  no-octal-escape: 2
  no-param-reassign: 1
  no-process-env: 0
  no-proto: 2
  no-return-assign: 2
  no-script-url: 2
  no-self-compare: 2
  no-sequences: 2
  no-shadow: 2
  no-shadow-restricted-names: 2
  no-spaced-func: 1
  no-this-before-super: 2
  no-throw-literal: 2
  no-trailing-spaces: 1
  no-undef: 2
  no-undef-init: 2
  no-unneeded-ternary: 2
  no-unused-expressions:
  - 2
  - allowShortCircuit: true
    allowTernary: true
  no-use-before-define: 2
  no-useless-call: 2
  no-useless-concat: 1
  no-void: 2
  no-with: 2
  operator-linebreak:
  - 2
  - before
  quote-props:
  - 2
  - as-needed
  quotes:
  - 1
  - single
  - avoid-escape
  radix:
  - 2
  - always
  require-yield: 2
  space-before-function-paren:
  - 1
  - never
  space-before-keywords: 0
  space-in-parens:
  - 1
  - never
  space-return-throw-case: 2
  strict:
  - 2
  - global
  wrap-iife:
  - 2
  - inside
  wrap-regex: 2
  yoda:
  - 2
  - never
