---
language: node_js
sudo: false

nodejs:
  - "5.4.1"
  - "stable"

compiler: clang-3.6

env:
  - CXX=clang-3.6

addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.6
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.6
      - gcc-4.9
      - g++-4.9

before_install:
  - npm install -g npm@3.5.3

install:
  - npm install
  - du -sh ./node_modules || true

script:
  - npm run build

cache:
  directories:
    - node_modules
